<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="bpmn" nsURI="http://www.example.org/bpmn" nsPrefix="bpmn">
  <eClassifiers xsi:type="ecore:EClass" name="BusinessProcessDiagram">
    <eStructuralFeatures xsi:type="ecore:EReference" name="pools" lowerBound="1" upperBound="-1"
        eType="#//Pool" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BPMNElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ID" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BPMNNode" eSuperTypes="#//BPMNElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="in" upperBound="-1" eType="#//Flow"
        eOpposite="#//Flow/out"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="out" upperBound="-1" eType="#//Flow"
        eOpposite="#//Flow/in"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Swimlane" abstract="true" eSuperTypes="#//BPMNElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Lane" eSuperTypes="#//Swimlane">
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
        eType="#//BPMNElement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Pool" eSuperTypes="#//Swimlane">
    <eStructuralFeatures xsi:type="ecore:EReference" name="lanes" lowerBound="1" upperBound="-1"
        eType="#//Lane" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Event" eSuperTypes="#//BPMNNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="StartEvent" eSuperTypes="#//Event"/>
  <eClassifiers xsi:type="ecore:EClass" name="EndEvent" eSuperTypes="#//Event"/>
  <eClassifiers xsi:type="ecore:EClass" name="IntermediateEvent" eSuperTypes="#//Event"/>
  <eClassifiers xsi:type="ecore:EClass" name="Activity" eSuperTypes="#//BPMNNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="Task" eSuperTypes="#//Activity"/>
  <eClassifiers xsi:type="ecore:EClass" name="Flow" eSuperTypes="#//BPMNElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="in" lowerBound="1" eType="#//BPMNNode"
        eOpposite="#//BPMNNode/out"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="out" lowerBound="1" eType="#//BPMNNode"
        eOpposite="#//BPMNNode/in"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SequenceFlow" eSuperTypes="#//Flow"/>
  <eClassifiers xsi:type="ecore:EClass" name="Association" eSuperTypes="#//Flow"/>
  <eClassifiers xsi:type="ecore:EClass" name="Gateway" eSuperTypes="#//BPMNNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="XORGateway" eSuperTypes="#//Gateway"/>
  <eClassifiers xsi:type="ecore:EClass" name="ORGateway" eSuperTypes="#//Gateway"/>
  <eClassifiers xsi:type="ecore:EClass" name="ANDGateway" eSuperTypes="#//Gateway"/>
  <eClassifiers xsi:type="ecore:EClass" name="Artifact" eSuperTypes="#//BPMNNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="Annotation" eSuperTypes="#//Artifact">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
